from .models import *

UNAVE = Department.create(name_dep='Associação para a Formação Profissional e Investigação da Universidade de Aveiro', acron_dep='UNAVE')
DLC = Department.create(name_dep='Departamento de Línguas e Culturas', acron_dep='DLC')
CONFUCIO = Department.create(name_dep='Antiga Reitoria', acron_dep='CONFUCIO')
DETI = Department.create(name_dep='Departamento de Electrónica, Telecomunicações e Informática', acron_dep='DETI')
DEP = Department.create(name_dep='Departamento de Educação e Psicologia', acron_dep='DEP')
SASUA = Department.create(name_dep='Serviços de Ação Social', acron_dep='SASUA')
DAO = Department.create(name_dep='Departamento de Ambiente e Ordenamento', acron_dep='DAO')
DBIO = Department.create(name_dep='Departamento de Biologia', acron_dep='DBIO')
DEMAC = Department.create(name_dep='Departamento de Engenharia de Materiais e Cerâmica', acron_dep='DEMAC')
DEGEIT = Department.create(name_dep='Departamento de Economia, Gestão e Engenharia Industrial e Turismo', acron_dep='DEGEIT')
DMAT = Department.create(name_dep='Departamento de Matemática', acron_dep='DMAT')
DCSPT = Department.create(name_dep='Departamento de Ciências Sociais, Políticas e do Território', acron_dep='DCSPT')
DFIS = Department.create(name_dep='Departamento de Física', acron_dep='DFIS')
DQ = Department.create(name_dep='Departamento de Química', acron_dep='DQ')
DGEO = Department.create(name_dep='Departamento de Geociências', acron_dep='DGEO')
BIBLIO = Department.create(name_dep='Biblioteca', acron_dep='BIBLIO')
DE = Department.create(name_dep='Departamento de Ciências da Educação', acron_dep='DE')
IT = Department.create(name_dep='Instituto de Telecomunicações', acron_dep='IT')
IEETA = Department.create(name_dep='Instituto de Engenharia Electrónica e Telemática de Aveiro', acron_dep='IEETA')
DECA = Department.create(name_dep='Departamento de Comunicação e Arte', acron_dep='DECA')
DEM = Department.create(name_dep='Departamento de Engenharia Mecânica', acron_dep='DEM')
CP = Department.create(name_dep='Complexo Pedagógico, Científico e Tecnológico', acron_dep='CP')
LIVRARIA = Department.create(name_dep='Livraria e Sala de Exposições', acron_dep='LIVRARIA')
REITORIA = Department.create(name_dep='Reitoria', acron_dep='REITORIA')
DBIO = Department.create(name_dep='Departamento de Biologia', acron_dep='DBIO')
DECIVIL = Department.create(name_dep='Departamento de Engenharia Civil', acron_dep='DECIVIL')
ISCA = Department.create(name_dep='Instituto Superior de Contabilidade e Administração', acron_dep='ISCA')
IDAD = Department.create(name_dep='Instituto de Ambiente e Desenvolvimento', acron_dep='IDAD')
CESAM = Department.create(name_dep='Centro de Estudos do Ambiente e do Mar', acron_dep='CESAM')
GRETUA = Department.create(name_dep='Grupo Experimental do Teatro da UA', acron_dep='GRETUA')
AAUAV = Department.create(name_dep='Casa do Estudante', acron_dep='AAUAV')

sw1 = Switch.create(identifier_switch='detiLab-b01-sw01.ua.pt', model_switch='cisco WS-C2950T-24', department=DETI)
sw2 = Switch.create(identifier_switch='detiLab-b01-sw02.ua.pt', model_switch='cisco WS-C2950T-48-SI', department=DETI)
sw3 = Switch.create(identifier_switch='detiLab-b02-sw01.ua.pt', model_switch='cisco WS-C2950T-24', department=DETI)

