# Generated by Django 3.0.5 on 2020-04-04 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audit_Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('ip_addr', models.GenericIPAddressField()),
                ('state', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VLAN',
            fields=[
                ('identifier', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=350)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssc_db_app.Port')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uu', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email_ua', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ssc_db_app.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('identifier', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssc_db_app.Department')),
                ('user_acess', models.ManyToManyField(to='ssc_db_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='port',
            name='switch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssc_db_app.Switch'),
        ),
        migrations.CreateModel(
            name='ACL',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('access_flag', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssc_db_app.User')),
            ],
        ),
    ]
