# Generated by Django 3.0.5 on 2020-04-04 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssc_db_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='switch',
            name='user_acess',
        ),
    ]
